CREATE TYPE "status" AS ENUM (
	'A_FAIRE',
	'TERMINE'
);

CREATE TYPE "role" AS ENUM (
	'admin',
	'member'
);

CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"role" ROLE NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"mail" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	"total_points" INTEGER,
	"created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "tasks" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"description" VARCHAR(255),
	"status" STATUS NOT NULL,
	"points" INTEGER,
	"created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "users_tasks" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"task_id" INTEGER NOT NULL,
	PRIMARY KEY("id"),
  CONSTRAINT fk_users FOREIGN KEY (user_id) --contrainte pour la clé étrangère
        REFERENCES users (id) MATCH SIMPLE -- références à la table correspondante
        ON DELETE CASCADE,
  CONSTRAINT fk_tasks FOREIGN KEY (task_id) --contrainte pour la clé étrangère
        REFERENCES tasks (id) MATCH SIMPLE -- références à la table correspondante
        ON DELETE CASCADE
);
