# Step 1 : nommer fichier ds GitHub Actions

name: CI

# Step 2 : déclencheur -> définit éléments qui lancent le workflow

on:
  # CI qd on push
  push:
    branches: ["**"] # ["**"] sur n'importe quelle branche (main / develop / branche-en-cours)
  # CI qd on ouvre ou modifie une PR
  pull_request:
    branches: ["**"]

# configure workflow = un ou plusieurs jobs qui s'exécutent en //
# 1 job = 1 vérification indépendante = 1 pipeline d'exécution
# ex: 1 job pour le front, 1 pr le back...

jobs:
  backend:
    # où est-ce que je fais les vérifs
    runs-on: ubuntu-latest # ds VM ubuntu fournie par GitHub
    # étapes du job backend
    defaults:
      run:
        # préciser que les commande que vous allez executer se font dans le dossier back
        working-directory: ./back
    steps:
      # 1. récupérer le code du repo sur la VM
      - name: 📥 Récupérer le code
        uses: actions/checkout@v4
      # 2. installer node.js
      - name: 🤯 Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # en plus de la version, préciser les mots-clés qu'on utilise derrière
          # ici le mot clé à utiliser en ligne de commande est 'npm' (gardé en mémoire dans le cache)
          cache: "npm"
      # 3. installer le projet
      - name: 🧱 Installer les dépendances
        run: npm ci
      # 4. builder le projet
      - name: 🏡 Builder le projet
        run: npm run build
      # 5. lancer les tests (optionnel pour le moment)
      - name: 🍿 Lancer les tests
        run: npm run test
